name: Build

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
      - "feature/**"
      - "fix/**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          # NOTE: This is only a matrix right now so it's easier when eventually setting up iOS
          - os: ubuntu-latest
            arch: x86_64

    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.35.3
          cache: true
      
      - name: Setup .env
        run: echo 'PASSWORD_SECRET_KEY="${{ secrets.PASSWORD_SECRET_KEY }}"' > .env

      - name: Build
        run: make build/android
      
      - name: Archive x86 APK
        uses: actions/upload-artifact@v4
        if: matrix.config.os == 'ubuntu-latest'
        with:
          name: bewcloud-x86-${{ github.sha }}-unsigned.apk
          path: build/app/outputs/flutter-apk/app-x86_64-release.apk
          if-no-files-found: error
      
      - name: Archive arm64 APK
        uses: actions/upload-artifact@v4
        if: matrix.config.os == 'ubuntu-latest'
        with:
          name: bewcloud-arm64-${{ github.sha }}-unsigned.apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          if-no-files-found: error
      
      - name: Archive armeabi APK
        uses: actions/upload-artifact@v4
        if: matrix.config.os == 'ubuntu-latest'
        with:
          name: bewcloud-armeabi-${{ github.sha }}-unsigned.apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          if-no-files-found: error
